Remade config system multi row print

diff --git a/bpdev b/bpdev
--- a/bpdev
+++ b/bpdev
@@ -242,7 +242,7 @@ tdim() { ##D Terminal dimensions
     cols=$(tput cols)
     echo "  Lines: ${lines} "
     echo "  Cols: ${cols}   "
-    echo -en "$E_CUR_RETURN${E_CUR_RETURN}"
+    echo -en "$E_RETURN${E_RETURN}"
   done
 
 }
@@ -357,11 +357,11 @@ cst() { ##D Color scheme tests
   aa "Default color scheme"
 
   BP_C_LINE="${E_DARKGRAY}"
-  BP_C_LINE_TEXT="${E_BR_YELLOW}"
+  BP_C_LINETEXT="${E_BR_YELLOW}"
   BP_C_DESCRIPTION="${E_BR_CYAN}"
-  BP_C_ID="${E_BR_MAGENTA}"
-  BP_C_FILENAME="${E_BR_GREEN}"
-  BP_C_PATH="${E_GREEN}"
+  BP_C_KEY="${E_BR_MAGENTA}"
+  BP_C_FILENAME="${E_BR_CYAN}"
+  BP_C_PATH="${E_CYAN}"
   BP_C_URL_SCHEME="${E_DARKGRAY}"
 
   aa "Makeplates color scheme"
@@ -469,17 +469,17 @@ completion() { ##D Print help information
 
   IFS=$'\n'
   SC="$1"
-  # HELP_LINES=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'help_line' -e 'printLine')
-  HELP_LINES=$(grep -h -e "##D" -e "##C" "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'help_line' -e 'printLine')
+  # HELP_LINES=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'LINE' -e 'printLine')
+  HELP_LINES=$(grep -h -e "##D" -e "##C" "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'LINE' -e 'printLine')
   HELP_LINES="${HELP_LINES//()/}"
 
-  for help_line in ${HELP_LINES}; do
-    case "$help_line" in
-    #    *"##-"*) printNamedLine "$help_line" ;;
-    #    *"##C-"*) printCondNamedLine "$help_line" ;;
-    #    *"##CV"*) printCondCommand "$help_line" 1 ;;
-    #    *"##C"*) XXprintCommand "$help_line" 0 ;;
-    *"##D"*) XXprintCommand "$help_line" '##D' ;;
+  for LINE in ${HELP_LINES}; do
+    case "$LINE" in
+    #    *"##-"*) printNamedLine "$LINE" ;;
+    #    *"##C-"*) printCondNamedLine "$LINE" ;;
+    #    *"##CV"*) printCondCommand "$LINE" 1 ;;
+    #    *"##C"*) XXprintCommand "$LINE" 0 ;;
+    *"##D"*) XXprintCommand "$LINE" '##D' ;;
     *) ;;
 
     esac
@@ -501,43 +501,6 @@ args() { ##D Test of arguments
   done
 }
 
-##- Update script
-kwr() { ##D Keyword replace
-  if [ ! -e "$2" ]; then
-    bpError "File ${2} does not exist"
-    bpExit
-  fi
-  bpReplace "$2" "bpText_TEMP_LineC" "bpText_TEMP_LineC"
-
-  bpReplace "$2" "bpPrintLine_deprecated() " "bpPrintLine_deprecated() "
-  bpReplace "$2" "bpPrintLine" "bpPrintLine"
-  bpReplace "$2" "bpPrintLineGeneric" "bpPrintLineGeneric"
-  bpReplace "$2" "bpPrintLine" "bpPrintLine"
-
-  bpReplace "$2" "bpText_TEMP_LineC" "bpText_TEMP_LineC"
-
-  bpReplace "$2" "bpRead()" "bpReadStr()"
-  bpReplace "$2" "bpRead " "bpReadStr "
-  bpReplace "$2" "bpReadYN" "bpReadBool"
-  bpReplace "$2" "bpReadY" "bpReadBoolDY"
-  bpReplace "$2" "bpReadN" "bpReadBoolDN"
-
-  bpReplace "$2" "_ATTR_" "_"
-  bpReplace "$2" "_CUR_" "_"
-
-  bpReplace "$2" "BP_E_OK" "BP_OK"
-  bpReplace "$2" "BP_C_LINE_TEXT" "BP_C_LINETEXT"
-
-  bpReplace "$2" "_FG_" "_"
-  bpReplaceLine "$2" "BP_C_FILENAME=" 'BP_C_FILENAME="${E_BR_CYAN}"'
-  bpReplaceLine "$2" "BP_C_PATH=" 'BP_C_PATH="${E_CYAN}"'
-
-  bpReplace "$2" "bpDbg" "bpDebug"
-
-  bpReplace "$2" "BP_SETTINGS" "BP_CONFIG"
-  bpReplace "$2" "bpPrintInfo" "bpPrintDesc"
-}
-
 LT="This is a very long text that does not fit into a single line, but have to be broken up with the help of an external command like for example fmt."
 bim() { ##D Break text into multiple lines
   SSH_KEY=~/.ssh/id_ed25519
@@ -545,9 +508,33 @@ bim() { ##D Break text into multiple lines
   #  bpPrintDescXX "Formated" "$LT"
 
   bpPrintLine "SSH"
-  # bpPrintDescXX "SSH public key location" "${SSH_KEY}.pub"
   bpPrintDesc "SSH public key" "$(cat "${SSH_KEY}.pub")"
+}
 
+set() { ##D Change setting in bp config file
+  BP_CONFIG_TEST=(
+    "config"
+    "Test config file"
+    "Setting1" "Default1" "Description 1"
+    "Setting2" "Default2" "Description 2"
+    "Setting3" "Default3" "Description 3"
+    "Setting4" "Default4" "Description 4"
+    "Setting5" "Default5" "Description 5"
+    "Setting6" "Default6" "Description 6"
+    "Setting7" "Default7" "Description 7"
+    "Setting8" "Default8" "Description 8"
+    "Setting9" "Default9" "Description 9"
+    "Setting10" "Default10" "Description 10"
+  )
+  if [ -z "$2" ]; then
+    bpConfPrint "" "" "${BP_CONFIG_TEST[@]}"
+    return
+  fi
+  bpConfChangeSetting "${2}" "${3}" "${BP_CONFIG_TEST[@]}"
+}
+
+conf() { ##D Config test
+  bpConfLoad "${BP_CONFIG_TEST[@]}"
 }
 
 #---------------------------------------------------------------------
@@ -797,8 +784,8 @@ BP_C_ERROR="${E_BR_RED}"
 BP_C_CRITICAL="${E_BG_RED}${E_WHITE}"
 BP_C_LINE="${E_DARKGRAY}"
 BP_C_LINETEXT="${E_YELLOW}"
-BP_C_DESCRIPTION="${E_GREEN}"
-BP_C_ID="${E_CYAN}"
+BP_C_DESCRIPTION="${E_CYAN}"
+BP_C_KEY="${E_BR_MAGENTA}"
 
 BP_C_FILENAME="${E_BR_CYAN}"
 BP_C_PATH="${E_CYAN}"
@@ -898,7 +885,7 @@ bpPrintDescGeneric() { # Generic key/description printout function
 # $3 (optional) left alignment
 #
 bpPrintDesc() { ##I Print key description
-  bpPrintDescGeneric "${BP_C_ID}" "${BP_C_DESCRIPTION}" "$1" "$2" "$3"
+  bpPrintDescGeneric "${BP_C_KEY}" "${BP_C_DESCRIPTION}" "$1" "$2" "$3"
 }
 
 bpPrintDescAlt() {
@@ -921,7 +908,7 @@ bpPrintVar() { ##I Print variable value and description
     fi
     bpPrintDesc "$1" "${X}"
   else
-    printf "${BP_C_ID}  %-24s${E_RESET} ${BP_C_ERROR}N/A${E_RESET}\n" "$1"
+    printf "${BP_C_KEY}  %-24s${E_RESET} ${BP_C_ERROR}N/A${E_RESET}\n" "$1"
   fi
 }
 
@@ -1278,9 +1265,9 @@ bpPrintChoiceList() { # Print items in selection list
     fi
 
     if [ "${desc}" == ":" ]; then
-      printf "${BP_C_ID} %-5s${E_RESET}%1s  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$default" "$val"
+      printf "${BP_C_KEY} %-5s${E_RESET}%1s  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$default" "$val"
     else
-      printf "${BP_C_ID} %-5s${E_RESET}%1s  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$default" "$desc"
+      printf "${BP_C_KEY} %-5s${E_RESET}%1s  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$default" "$desc"
     fi
   done
 }
@@ -1330,6 +1317,7 @@ bpSelectFromList() { ##I Select from list
 # Settings file ------------------------------------------------------
 
 ##C- BP_CONF Bashplate config file
+##C- IHELP Bashplate config file
 
 #
 # $1 config file
@@ -1344,6 +1332,8 @@ bpAddSetting() { ##I Add setting to config file
       echo "${2}=\"${3}\""
       echo
     } >>"${1}"
+
+    bpOk "Added setting \"$2=$3\""
   fi
 }
 
@@ -1352,18 +1342,68 @@ bpAddSetting() { ##I Add setting to config file
 # $1 config file
 # $2 key
 # $3 value
+# $4 description
 #
-bpChSetting() { ##I Change setting in config file
-  SETTING="$2"
+bpChangeSetting() { ##I Change setting in config file
+  FILE="$1"
+  KEY="$2"
   VAL="$3"
-
-  S=$(bpStrExist "${1}" "${2}")
-  if [ "${S}" == "0" ]; then
-    bpAddSettings ""
+  DESC="$4"
+  if ! bpStrExist "${1}" "${KEY}"; then
+    bpAddSetting "$FILE" "$KEY" "$VAL" "$DESC"
   fi
-  sed -i "s/^\(${SETTING}\s*=\s*\).*\$/\1$VAL/" "$1"
+  sed -i "s/^\(${KEY}\s*=\s*\).*\$/\1\"${VAL}\"/" "${FILE}"
+  bpOk "Changing ${KEY} to ${VAL}"
+}
 
-  bpOk "Setting ${SETTING} to ${VAL}"
+#
+# $1 key
+# $2 config array
+#
+bpConfGetDesc() { ##I Get config desription
+  arr=("${@:1}")
+  len=${#arr[@]}
+  bpReturn=""
+  i=1
+  while [ "$i" -lt "$len" ]; do
+    key=${arr[$i]}
+    ((i++))
+    def=${arr[$i]}
+    ((i++))
+    desc=${arr[$i]}
+    ((i++))
+    #echo "$key"
+    if [ "$key" == "$1" ]; then
+      echo "$desc"
+      return 0
+    fi
+  done
+  return 1
+}
+
+#
+# $1 key
+# $2 value
+# $3 config array
+#
+bpConfChangeSetting() {
+  KEY="$1"
+  VAL="$2"
+  CONF=("${@:2}")
+  FILE=${CONF[1]}
+  DESC=$(bpConfGetDesc "$KEY" "${CONF[@]}")
+
+  if ! bpConfInList "$KEY" "${CONF[@]}"; then
+    bpError "\"$KEY\" is not a valid setting"
+    return
+  fi
+
+  if ! bpStrExist "${FILE}" "${KEY}"; then
+    bpAddSetting "${FILE}" "$KEY" "$VAL" "${DESC}"
+    return "$BP_OK"
+  fi
+
+  bpChangeSetting "$FILE" "$KEY" "$VAL" "$DESC"
 }
 
 #
@@ -1371,7 +1411,7 @@ bpChSetting() { ##I Change setting in config file
 # $2 Headertext
 # $3 config array
 #
-bpCreateConfigFile() { ##I Create configuration file
+bpConfCreate() { ##I Create configuration file
   FILE="$1"
   {
     echo "# "
@@ -1384,8 +1424,6 @@ bpCreateConfigFile() { ##I Create configuration file
   len=${#arr[@]}
   i=1
   while [ "$i" -lt "$len" ]; do
-    name=${arr[$i]}
-    ((i++))
     key=${arr[$i]}
     ((i++))
     default=${arr[$i]}
@@ -1396,83 +1434,72 @@ bpCreateConfigFile() { ##I Create configuration file
   done
 }
 
-bpLoadConfigFile() { ##I Load config file
+#
+# $1 Config file
+#
+bpConfLoad() { ##I Load config file
   if [ -n "${1}" ]; then
-    if [ -e "${1}" ]; then
-      source "${1}"
-    else
-      bpCreateConfigFile "${@}"
-      source "${1}"
+    if [ ! -e "${1}" ]; then
+      bpConfCreate "${@}"
     fi
+    source "${1}"
   fi
 }
 
-bpInConfigList() { ##I Check if setting exist in config file
-  arr=("${@}")
+#
+# $1 key
+# $2 config array
+#
+bpConfInList() { ##I Check if key exist in config file list
+  arr=("${@:1}")
   len=${#arr[@]}
   bpReturn=""
-  i=3
+  i=1
   while [ "$i" -lt "$len" ]; do
     key=${arr[$i]}
     ((i++))
-    val=${arr[$i]}
-    ((i++))
+    def=${arr[$i]}
     ((i++))
     desc=${arr[$i]}
     ((i++))
-
+    #echo "$key"
     if [ "$key" == "$1" ]; then
-      if [ "$val" == ":" ]; then
-        bpReturn="${key}"
-      else
-        bpReturn="${val}"
-      fi
       return 0
     fi
   done
   return 1
 }
 
-bpPrintConfigList() { ##I Print settings in config list
+bpConfPrint() { ##I Print settings in config list
+  echo
+  bpPrintDesc "Config file" "$(bpColorizeFile "$3")"
   echo
   arr=("${@:4}")
-  len=${#arr[@]}
   i=1
-  while [ "$i" -lt "$len" ]; do
+  while [ "$i" -lt ${#arr[@]} ]; do
     key=${arr[$i]}
     ((i++))
-    val=${arr[$i]}
-    ((i++))
+    def=${arr[$i]}
     ((i++))
     desc=${arr[$i]}
     ((i++))
-
-    if [ "${desc}" == ":" ]; then
-      printf "${BP_C_ID} %-12s${E_RESET}  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$val"
-    else
-      printf "${BP_C_ID} %-12s${E_RESET}  ${BP_C_DESCRIPTION}%s${E_RESET}\n" "$key" "$desc"
-    fi
+    eval "val=\$$key"
+    #bpPrintLine "${desc}"
+    printf "%s%s\n" "${E_DARKGRAY}" "${desc}"
+    bpPrintDesc "$key" "$val"
   done
 }
 
-bpset() { ##D Change setting in bp config file
-
-  if bpInConfigList "$2" "${BP_CONFIG_LIST[@]}"; then
-    bpChSetting "${BP_CONFIG_FILE}" "${bpReturn}" "\"${3}\""
+bpset() { ##C BP_CONF Change setting in bp config file
+  if [ -z "$2" ]; then
+    bpConfPrint "" "" "${BP_CONFIG_LIST[@]}"
     return
   fi
-  bpPrintConfigList "" "" "${BP_CONFIG_LIST[@]}"
-}
-
-settings() { ##C BP_CONF Print bashplate settings
-  bpPrintLine "Bashplates settings"
-  bpPrintVar "Name:" BP_NAME
-  bpPrintVar "Email:" BP_EMAIL
-  bpPrintVar "Default license:" BP_LICENSE
-  bpPrintVar "Default editor" BP_EDITOR
-  bpPrintVar "Default organisation" BP_ORG
-  bpPrintVar "Default diff program" BP_DIFF
-  bpPrintLine
+  if bpConfInList "$2" "${BP_CONFIG_LIST[@]}"; then
+    bpChangeSetting "${BP_CONFIG_FILE}" "${bpReturn}" "\"${3}\""
+    return
+  fi
+  bpError "\"$2\" is not a valid setting"
 }
 
 ##C- IHELP Bashrc path/module handling
@@ -1743,16 +1770,16 @@ irt() { ##I Remove tabs from script
 
 printCommand() {
   IFS=$' '
-  read -r -a arr <<<"$1"
-  inf="${arr[*]:3}"
-  bpPrintDesc "${arr[0]}" "${inf}"
+  read -r -a LINE <<<"$1"
+  DESC="${LINE[*]:3}"
+  bpPrintDesc "${LINE[0]}" "${DESC}"
 }
 
 printCondCommand() {
   IFS=$' '
-  read -r -a arr <<<"$1"
-  help_info="${arr[*]:4}"
-  COND=${arr[3]}
+  read -r -a LINE <<<"$1"
+  DESC="${LINE[*]:4}"
+  COND=${LINE[3]}
   eval "D=\$$COND"
 
   if [ -n "$IHELP" ] && [ "$COND" != "IHELP" ]; then
@@ -1760,31 +1787,35 @@ printCondCommand() {
   fi
 
   if [ -n "$D" ]; then
-    bpPrintDesc "${arr[0]}" "${help_info}"
+    bpPrintDesc "${LINE[0]}" "${DESC}"
     return
   fi
 
   if [ "$2" -eq 1 ]; then
-    bpPrintDescAlt "${arr[0]}" "$help_info"
+    bpPrintDescAlt "${LINE[0]}" "${DESC}"
   fi
 
 }
 
 printNamedLine() {
   IFS=$' '
-  read -r -a arr <<<"$1"
-  info=${arr[*]:1}
-  bpPrintLine "${info}"
+  read -r -a LINE <<<"$1"
+  bpPrintLine "${LINE[*]:1}"
 }
 
 printCondNamedLine() {
   IFS=$' '
-  read -r -a arr <<<"$1"
-  name=${arr[*]:2}
-  COND=${arr[1]}
+  read -r -a LINE <<<"$1"
+  DESC=${LINE[*]:2}
+  COND=${LINE[1]}
   eval "D=\$$COND"
+
+  if [ -n "$IHELP" ] && [ "$COND" != "IHELP" ]; then
+    return
+  fi
+
   if [ -n "$D" ]; then
-    bpPrintLine "$name"
+    bpPrintLine "$DESC"
   fi
 }
 
@@ -1806,16 +1837,16 @@ help() { ##D Print help information
 
   IFS=$'\n'
   SC="$1"
-  HELP_LINES=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'help_line' -e 'printLine')
-  HELP_LINES="${HELP_LINES//()/}"
+  LINES=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'LINE' -e 'printLine')
+  LINES="${LINES//()/}"
 
-  for help_line in ${HELP_LINES}; do
-    case "$help_line" in
-    *"##-"*) printNamedLine "$help_line" ;;
-    *"##C-"*) printCondNamedLine "$help_line" ;;
-    *"##CV"*) printCondCommand "$help_line" 1 ;;
-    *"##C"*) printCondCommand "$help_line" 0 ;;
-    *"##D"*) printCommand "$help_line" '##D' ;;
+  for LINE in ${LINES}; do
+    case "$LINE" in
+    *"##-"*) printNamedLine "$LINE" ;;
+    *"##C-"*) printCondNamedLine "$LINE" ;;
+    *"##CV"*) printCondCommand "$LINE" 1 ;;
+    *"##C"*) printCondCommand "$LINE" 0 ;;
+    *"##D"*) printCommand "$LINE" '##D' ;;
     *) ;;
 
     esac
@@ -1850,14 +1881,14 @@ ihelp() { ##I Print internal help information
   IHELP=1      # Force ihelp documentations
   BP_LOGFILE=1 # Force log documentation
 
-  help_lines=$(grep -h '##[C|I]' "$0" | grep -v -e 'grep' -e '\*"##[ A-Z]"\*' -e 'help_line' -e 'printNamedLine' -e 'awk' -e 'bpPrintDesc' -e 'name')
-  help_lines=$(echo -e "$help_lines" | sed -s 's/()//g')
+  LINES=$(grep -h '##[C|I]' "$0" | grep -v -e 'grep' -e '\*"##[ A-Z]"\*' -e 'LINE' -e 'printNamedLine' -e 'awk' -e 'bpPrintDesc' -e 'name')
+  LINES=$(echo -e "$LINES" | sed -s 's/()//g')
 
-  for help_line in ${help_lines}; do
-    case "$help_line" in
-    *"##C-"*) printCondNamedLine "$help_line" ;;
-    *"##I"*) printCommand "$help_line" '##I' ;;
-    *"##C"*) printCondCommand "$help_line" 0 ;;
+  for LINE in ${LINES}; do
+    case "$LINE" in
+    *"##C-"*) printCondNamedLine "$LINE" ;;
+    *"##I"*) printCommand "$LINE" '##I' ;;
+    *"##C"*) printCondCommand "$LINE" 0 ;;
     *) ;;
 
     esac
@@ -1866,9 +1897,9 @@ ihelp() { ##I Print internal help information
   bpPrintLine "Bashplates comments"
   bpPrintDesc "##D Description" "Subcommand information comment (shown with help)"
   bpPrintDesc "##C COND Description" "Conditional subcommand comment (shown with help)"
+  bpPrintDesc "##I Description" "Internal function comment (shown with ihelp)"
   bpPrintDesc "##- [Text]" "Separator line (shown with help)"
   bpPrintDesc "##C- COND [Text]" "Conditional separator line (shown with help)"
-  bpPrintDesc "##I Description" "Internal function comment (shown with ihelp)"
   bpPrintLine
 }
 
@@ -1936,13 +1967,13 @@ ivars() { ##I Print internal variables
   bpPrintLine "Script variables"
   echo
   IFS=$'\n'
-  help_lines=$(grep -v -e 'help_lines' -e 'help_line' "$0" | grep -A 1 '##V') # | sed "s/--//" )
-  for line in ${help_lines}; do
+  LINES=$(grep -v -e 'LINES' -e 'LINE' "$0" | grep -A 1 '##V') # | sed "s/--//" )
+  for line in ${LINES}; do
     if [ "$line" == "--" ]; then
       echo
     else
-      help_line=$(echo "${line}" | sed -u -e "s/##V[ ]/${BP_C_DESCRIPTION}/i" -e "s/^.*=/${BP_C_ID}&${E_RESET}/i" -e "s/=/${E_RESET}=/")
-      echo -e "$help_line"
+      LINE=$(echo "${line}" | sed -u -e "s/##V[ ]/${BP_C_DESCRIPTION}/i" -e "s/^.*=/${BP_C_KEY}&${E_RESET}/i" -e "s/=/${E_RESET}=/")
+      echo -e "$LINE"
       echo -en "$E_RESET"
     fi
   done
@@ -2074,16 +2105,17 @@ trap 'signalErr ${FUNCNAME} ${LINENO}' ERR
 BP_CONFIG_LIST=(
   "${BP_CONFIG_FILE}"
   "Bashplates common settings"
-  "name" "BP_NAME" "John Doe" "Users name"
-  "email" "BP_EMAIL" "john.doe@foo.bar" "Users email"
-  "org" "BP_ORG" "ACME" "Organisation"
-  "license" "BP_LICENSE" "MIT" "Default license"
-  "editor" "BP_EDITOR" "vi" "Default editor"
-  "diff" "BP_DIFF" "meld" "Default diff program"
+  "BP_NAME" "John Doe" "Users name"
+  "BP_EMAIL" "john.doe@foo.bar" "Users email"
+  "BP_ORG" "ACME" "Organisation"
+  "BP_LICENSE" "MIT" "Default license"
+  "BP_EDITOR" "vi" "Default editor"
+  "BP_DIFF" "meld" "Default diff program"
+  "BP_TMP" "tmp" "Default temporary setting"
 )
 
 # Load configuration file settings
-bpLoadConfigFile "${BP_CONFIG_LIST[@]}"
+bpConfLoad "${BP_CONFIG_LIST[@]}"
 
 # execute prescript hook if existing
 if [ -n "$PRE_SCRIPT_HOOK" ]; then
