Added color example

diff --git a/example b/example
--- a/example
+++ b/example
@@ -9,13 +9,107 @@
 #---------------------------------------------------------------------
 #
 
-# Basedir for script
-#
-basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+#---------------------------------------------------------------------
+# User Settings
+#---------------------------------------------------------------------
 
 # logfile
-#
-logfile=/var/log/logfile.log
+LOGFILE=/var/log/bashplate-example.log
+
+# Script version info
+VERSION="example 1.03"
+
+# Usage info
+USAGE="Usage: example command [option]" 
+
+# Description
+DESC="Bashplate is a bash script template to ease development of\n\
+command style shellscripts"
+
+
+#---------------------------------------------------------------------
+# User functions
+#---------------------------------------------------------------------
+
+info() { # Display rows and columns
+  echo $LINES
+	echo "Columns: ${COLUMNS}"
+}
+
+print_bar() {
+  echo -n " ["
+	for jx in `seq 1 $2`; do
+	  echo -n "="
+	done
+	for jx in `seq 1 $(expr $1 - $2)`; do
+	  echo -n " "
+	done
+	echo  "]"   
+}
+
+bar() { ## print a testbar (ANSI) 
+  echo -en $E_HIDE
+  for i in `seq 1 30`;
+	do
+	  sleep 0.03
+		print_bar 30 $i
+		echo -e $E_RETURN $E_UP 
+	done
+  echo -en $E_SHOW
+}
+
+clean() { ## Remove leftover files
+  find . -name "*~" -delete
+}
+
+
+traper() {
+  echo "Traped SIGINT"
+	exit
+}
+
+traptest() { ## Trap signal test
+  # trap the signal SIGINT to function traper
+	trap traper SIGINT
+
+  for i in $(seq 1 30); do
+	  sleep 0.1
+	  echo "Wating"
+	done
+}
+
+colors() { ## Color test
+  echo -e "${E_RED}RED${E_END}"
+	echo -e "${E_GREEN}GREEN${E_END}"
+	echo -e "${E_YELLOW}YELLOW${E_END}"
+  echo -e "${E_BLUE}BLUE${E_END}"
+	echo -e "${E_MAGENTA}MAGENTA${E_END}"
+	echo -e "${E_CYAN}CYAN${E_END}"
+	echo -e "${E_GRAY}GRAY${E_END}"
+	echo -e "${E_DARKGRAY}DARKGRAY${E_END}"
+  echo -e "${E_BOLD_RED}BOLD RED${E_END}"
+	echo -e "${E_BOLD_GREEN}BOLD GREEN${E_END}"
+	echo -e "${E_BOLD_YELLOW}BOLD YELLOW${E_END}"
+  echo -e "${E_BOLD_BLUE}BOLD BLUE${E_END}"
+	echo -e "${E_BOLD_MAGENTA}BOLD MAGENTA${E_END}"
+	echo -e "${E_BOLD_CYAN}BOLD CYAN${E_END}"
+	echo -e "${E_WHITE}WHITE${E_END}"
+	
+	echo -e "${E_WHITE}${ON_RED}WHITE on RED${E_END}"
+	echo -e "${E_WHITE}${ON_GREEN}WHITE on GREEN${E_END}"
+	echo -e "${E_WHITE}${ON_YELLOW}WHITE on YELLOW${E_END}"
+	echo -e "${E_WHITE}${ON_BLUE}WHITE on BLUE${E_END}"
+	echo -e "${E_WHITE}${ON_MAGENTA}WHITE on MAGENTA${E_END}"
+	echo -e "${E_WHITE}${ON_CYAN}WHITE on CYAN${E_END}"	
+}
+
+
+#--------------------------------------------------------------------- 
+# System functions and settings
+#---------------------------------------------------------------------
+
+# Basedir for script
+basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 # ANSI foreground colors codes
 #
@@ -34,18 +128,18 @@ E_BOLD_YELLOW='\e[1;33m'  # Bold Yellow
 E_BOLD_BLUE='\e[1;34m'    # Bold Blue
 E_BOLD_MAGENTA='\e[1;35m' # Bold Magenta
 E_BOLD_CYAN='\e[1;36m'    # Bold Cyan
-E_BOLD_WHITE='\e[1;37m'   # White
+E_WHITE='\e[1;37m'        # White
 
 # ANSI background color codes
 #
-On_Black='\e[40m'         # Black
-On_Red='\e[41m'           # Red
-On_Green='\e[42m'         # Green
-On_Yellow='\e[43m'        # Yellow
-On_Blue='\e[44m'          # Blue
-On_Purple='\e[45m'        # Purple
-On_Cyan='\e[46m'          # Cyan
-On_White='\e[47m'         # White
+ON_BLACK='\e[40m'         # Black
+ON_RED='\e[41m'           # Red
+ON_GREEN='\e[42m'         # Green
+ON_YELLOW='\e[43m'        # Yellow
+ON_BLUE='\e[44m'          # Blue
+ON_MAGENTA='\e[45m'       # Magenta
+ON_CYAN='\e[46m'          # Cyan
+ON_WHITE='\e[47m'         # White
 
 # ANSI cursor operations
 #
@@ -63,37 +157,6 @@ printLine() {
   echo -e "${E_BOLD_WHITE}------------------------------------------------------------------------------${E_END}"
 }
 
-#--------------------------------------------------------------------- 
-# Add your code after here 
-#---------------------------------------------------------------------
-
-info() { ## Display rows and columns
-  echo $LINES
-	echo "Columns: ${COLUMNS}"
-}
-
-
-print_bar() {
-  echo -n " ["
-	for jx in `seq 1 $2`; do
-	  echo -n "="
-	done
-	for jx in `seq 1 $(expr $1 - $2)`; do
-	  echo -n " "
-	done
-	echo  "]"   
-}
-
-test() { ## test command
-  echo -en $E_HIDE
-  for i in `seq 1 30`;
-	do
-	  sleep 0.03
-		print_bar 30 $i
-		echo -e $E_RETURN $E_UP 
-	done
-  echo -en $E_SHOW
-}
 
 
 #--------------------------------------------------------------------- 
@@ -104,14 +167,12 @@ test() { ## test command
 # Function logging to file
 #
 # Arg1 String to log to file
-#
+# 
 fnLog() {
-  #ts=´date +"%Y-%m-%d %H:%M:%S 
-	echo $ts $1 >> $logfile
+  ts=$(date +"%Y-%m-%d %H:%M:%S")
+	echo $ts $1 >> $LOGFILE
 }
 
-
-#
 # Change setting in config file (key value pair)
 #
 # arg1 config file
@@ -125,8 +186,10 @@ chSetting() {
 }
 
 help() { ## Print this help information
-  echo 
-	printf "%-20s  %s\n" "Target" "Help"
+	echo $USAGE
+	echo -e $DESC
+	echo 
+	printf "%-20s  %s\n" "Command" "Help"
 	printLine
 	IFS=$'\n'
   help_lines=`grep -h "##" $0 | grep -v grep | grep -v help_line`
@@ -140,8 +203,17 @@ help() { ## Print this help information
 	echo
 }
 
+version() { ## Print version information
+  echo $VERSION
+}
+
 # Runs a function in this file as a command
-runCommand() { 
+runCommand() {
+	if [ $# == "1" ]; then
+	  echo -e ${E_BOLD_RED}"No command given"${E_END}
+		help
+		exit
+	fi
   funks=`grep "##" $0 | grep -v grep | grep -v help_line`
 	for line in ${funks[@]}; do
 	  command=`echo $line | sed -s 's/(.*//'`
@@ -150,7 +222,9 @@ runCommand() {
 			exit
 		fi
 	done
-	help	
+	echo -e ${E_BOLD_RED}"Command not found"${E_END}
+	help
+	exit 
 }
 
 runCommand $1 $2 $3 $4 $5 $6 $7 $8 $9 $10
